name: Check i18n files
on:
  pull_request:
    branches:
      - master
jobs:
  check-i18n-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install python babel
        run: sudo apt-get install python-babel
      - uses: actions/checkout@v2
      - name: Check i18n files
        run: |
          pybabel extract -o messages.pot . && pybabel update -i messages.pot -d grading/uncode/lang
          file="grading/uncode/lang/es/LC_MESSAGES/messages.po"
          inserted="$(git diff --numstat $file | cut -f1)"
          inserted=$((inserted + 0))
          deleted="$(git diff --numstat $file | cut -f2)"
          deleted=$((deleted + 0))
          echo "$(git diff)"
          if [ $inserted -gt 2 ] || [ $deleted -gt 2 ]; then
              echo "The translation files are not updated. Please update the translations files in grading/uncode/lang to merge this PR.";
              exit 1;
          fi
  check-i18n-files-compiled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install python babel
        run: sudo apt-get install python-babel
      - uses: actions/checkout@v2
      - name: Check i18n files
        run: |
          pybabel compile -d grading/uncode/lang
          total_changed="$(git diff --stat | wc -l)"
          total_changed=$((total_changed + 0))
          if [ $total_changed -gt 0 ]; then
              echo "The translation files are not compiled. Run the compilation command to update them.";
              exit 1;
          fi